### ISSUE TITLE
Colors not working properly.

### ISSUE THREAD

**Issue by redoxahmii** [nobbmaestro/nvim-andromeda#3]
### Loved the theme on vscode decided to try it here but the highlighting does not seem to be working properly for HTML

![image](https://github.com/nobbmaestro/nvim-andromeda/assets/13983258/c93415a2-06d7-42f8-a16e-256c45794307)

The import colors are also not really workng properly and HTML issues are apparent as it is.
Any guidance or information about bug fixes?

**Comment by nobbmaestro** [comment]
Well, have been checking into this. The issue appears to be that tsx is a parser of its own and therefore, the already-implemented js and html configs are not utilized.  Since I have not developed any configuration for tsx, the fallback highlighting is being used. 

I will let you know once an implementation is in place.

**Comment by redoxahmii** [comment]
Sure I'll be waiting

**Comment by Dishant1804** [comment]
@nobbmaestro Any updates on this issue? Further more the colors are not getting overridden could you please assist me with it

![Screenshot from 2024-01-04 11-06-52](https://github.com/nobbmaestro/nvim-andromeda/assets/115367435/fd31ae00-a9bd-4e14-adf7-e460535d9e8c)

**Comment by nobbmaestro** [comment]
As a matter of fact, there is fix on development branch. However, I've not released it yet. If you are using lazy.nvim, you may add `branch = "development` to access the progress. 

Regarding the background color, I'm not able to reproduce it. Works just fine for me. Perhaps you could try to set `transparent_bg = true` and let the terminal decide the background color?

**Comment by nobbmaestro** [comment]
> Sure I'll be waiting

I have just pushed a release containing configuration files for ts. However, I have not addressed "incorrect highlighting for imports" since I do not agree that these are incorrect. In the given example, you are importing types and tree-sitter is applying highlight group "@types". Therefore, the components are highlighted as yellow.

**Comment by nobbmaestro** [comment]
> Sure I'll be waiting

I have just pushed a release containing configuration files for ts. However, I have not addressed "incorrect highlighting for imports" since I do not agree that these are incorrect. In the given example, you are importing types and tree-sitter is applying highlight group "@types". Therefore, the components are highlighted as yellow.

**Comment by redoxahmii** [comment]
> > Sure I'll be waiting
> 
> I have just pushed a release containing configuration files for ts. However, I have not addressed "incorrect highlighting for imports" since I do not agree that these are incorrect. In the given example, you are importing types and tree-sitter is applying highlight group "@types". Therefore, the components are highlighted as yellow.

By incorrect i meant they were not the same as compared to VScode but that is not too much of an issue.
Thanks for the good work.
